#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Log-Trace
Version  : 1.070
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BB/BBC/Log-Trace-1.070.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BB/BBC/Log-Trace-1.070.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblog-trace-perl/liblog-trace-perl_1.070-3.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-Log-Trace-license
Requires: perl-Log-Trace-man

%description
Log::Trace v1.070
(c) BBC 2004. This program is free software; you can redistribute it and/or modify it under the GNU GPL.

%package license
Summary: license components for the perl-Log-Trace package.
Group: Default

%description license
license components for the perl-Log-Trace package.


%package man
Summary: man components for the perl-Log-Trace package.
Group: Default

%description man
man components for the perl-Log-Trace package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Log-Trace-1.070
mkdir -p %{_topdir}/BUILD/Log-Trace-1.070/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Log-Trace-1.070/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Log-Trace
cp COPYING %{buildroot}/usr/share/doc/perl-Log-Trace/COPYING
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Log-Trace/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Log/Trace.pm
/usr/lib/perl5/site_perl/5.26.1/Log/Trace/Manual.pod

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Log-Trace/COPYING
/usr/share/doc/perl-Log-Trace/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Log::Trace.3
/usr/share/man/man3/Log::Trace::Manual.3
